### ISSUE TITLE
Error while importing pyecsim

### ISSUE THREAD

**Issue by bbmt** [Limhes/ecsim#1]
import pyecsim returns the following error:

Simulation: PyType_Ready failed (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 270: invalid start byte)!

**Comment by Limhes** [comment]
Hi, did you install via pip or compile yourself? Could you give some code and information about platform and python version? Thanks

**Comment by bbmt** [comment]
I installed via pip. I'm using win10, python 3.7.6.

**Comment by Limhes** [comment]
The issue should be resolved in version 0.2.3. Would you care to update, try again and report if it works? Thanks.

`pip install pyecsim --user --upgrade`

Problem was an invalid character in the docstring of the Simulation class in pyecsim.cpp, which gave an error on Windows.

**Comment by Limhes** [comment]
I assume the issue is resolved, since it worked for me on two different machines using Win10 and Python 3.7.
